datasources:
  default:
    url: jdbc:tc:postgresql:11.4://localhost/basilisk?user=basilisk
    username: basilisk
    password: ""
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
