datasources:
  default:
    url: jdbc:postgresql://localhost:5432/basilisk?user=basilisk
    username: basilisk
    password: ""
    driver-class-name: org.postgresql.Driver

endpoints:
  all:
    enabled: true
    path: /admin
    sensitive: false
  health:
    details-visible: ANONYMOUS

flyway:
  datasources:
    default:
      locations: classpath:db/migration

micronaut:
  application:
    name: basilisk-kt
  router:
    static-resources:
      swagger:
        mapping: /swagger/**
        paths: classpath:META-INF/swagger
