endpoints:
  all:
    enabled: true
    path: /admin
    sensitive: false
  health:
    details-visible: ANONYMOUS

swagger:
  urls:
    - name: basilisk
      url: /api-docs/swagger/basilisk-0.yml

micronaut:
  application:
    name: basilisk-kt
    instance: ${random.uuid}
    version: 0
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: ${swagger.path}/**

tracing:
  zipkin:
    enabled: true
    sampler:
      probability: 1
