micronaut:
  application:
    name: basil
    instance: ${random.uuid}
    version: 0
  server:
    port: 7371

# Duplicate for each bin, until
# https://github.com/micronaut-projects/micronaut-core/issues/517 resolved
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/basil
    username: basilisk
    password: ""
    driver-class-name: org.postgresql.Driver  # TODO: Is JDBC URL not enough?
