micronaut:
  application:
    name: chefs
    instance: ${random.uuid}
    version: 0
  server:
    port: 7372

# Duplicate for each bin, until
# https://github.com/micronaut-projects/micronaut-core/issues/517 resolved
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/basilisk?currentSchema=chefs
    username: basilisk
    password: ""
    driver-class-name: org.postgresql.Driver
