CREATE TABLE IF NOT EXISTS LOCATION
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    "NAME" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CHEF
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    "NAME" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS RECIPE
(
    ID      INT AUTO_INCREMENT PRIMARY KEY,
    "NAME"  TEXT NOT NULL,
    CHEF_ID INT  NOT NULL,
    CONSTRAINT FK_RECIPE_CHEF_ID_ID FOREIGN KEY (CHEF_ID) REFERENCES CHEF (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS SOURCE
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    "NAME" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS INGREDIENT
(
    ID        INT AUTO_INCREMENT PRIMARY KEY,
    "NAME"    TEXT NOT NULL,
    CHEF_ID   INT  NOT NULL,
    RECIPE_ID INT  NULL,
    SOURCE_ID INT  NOT NULL,
    CONSTRAINT FK_INGREDIENT_CHEF_ID_ID FOREIGN KEY (CHEF_ID) REFERENCES CHEF (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_INGREDIENT_RECIPE_ID_ID FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_INGREDIENT_SOURCE_ID_ID FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS TRIP
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    "NAME" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS LEG
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    TRIP_ID  INT NOT NULL,
    START_ID INT NOT NULL,
    END_ID   INT NOT NULL,
    CONSTRAINT FK_LEG_TRIP_ID_ID FOREIGN KEY (TRIP_ID) REFERENCES TRIP (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_LEG_START_ID_ID FOREIGN KEY (START_ID) REFERENCES LOCATION (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_LEG_END_ID_ID FOREIGN KEY (END_ID) REFERENCES LOCATION (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
