datasources:
  default:
    url: jdbc:postgresql://localhost:5432/basilisk?user=basilisk
    username: basilisk
    password: ""
    driver-class-name: org.postgresql.Driver

endpoints:
  all:
    enabled: true
    path: /admin
    sensitive: false
  health:
    details-visible: ANONYMOUS

swagger:
  path: /api-docs/swagger
  version: 3  # Latest version, let UI get improvements automatically
  layout: StandaloneLayout
  deepLinking: true
  displayRequestDuration: true
  showCommonExtensions: true
  showExtensions: true
  urls:
    - name: basilisk
      url: /api-docs/swagger/basilisk-0.yml

micronaut:
  application:
    name: basilisk-kt
    instance: ${random.uuid}
    version: 0
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: ${swagger.path}/**

tracing:
  zipkin:
    enabled: true
    sampler:
      probability: 1
